name: SpawnTP
author: LaxWasHere
version: 1.4.5
main: net.lazlecraft.spawntp.SpawnTP
commands:
    setspawn:
        description: Sets the spawn point
        aliases: sss
        permission: spawntp.setspawn
        permission-message: You may not set the spawn.
    spawn:
        description: Sends you to the world spawn.
        permissions: spawntp.spawn
        permission-message: You may not go to spawn!
    spawnloc:
        description: Tells you the coordinates of spawn
        permissions: spawntp.location
        permission-message: You may not have the spawn location!
    spawntp:
        description: Tells you info about the plugin and reloads the plugin.