name: SpawnTP
author: LaxWasHere
version: ${project.version}
main: net.lazlecraft.spawntp.SpawnTP
commands:
    setspawn:
        description: Sets the spawn point
        aliases: sss
        permission: spawntp.setspawn
        permission-message: You may not set the spawn.
    spawn:
        description: Sends you to spawn.
        permissions: spawntp.spawn
        permission-message: You may not go to spawn!
    spawnloc:
        description: Tells you the coordinates of spawn
        permissions: spawntp.location
        permission-message: You may not have the spawn location!
    setworldspawn:
        description: Sets the worlds spawn
        permissions: spawntp.setworldspawn
        permission-message: You may not set the world spawn!
    worldspawn:
        description: Sends you to the world spawn.
        permissions: spawntp.worldspawn
        permission-message: You may not go to the world spawn!
    spawntp:
        description: Tells you info about the plugin and reloads the plugin.